export enum Errors {
  POST_ID_MISSING = "Post id is missing",
  ALL_FIELDS_REQUIRED = "All Fields Are Required",
  INVALID_USERNAME = "Invalid username",
  INVALID_EMAIL = "Invalid email",
  WEAK_PASSWORD = "Weak password",
  DUPLICATE_USERNAME = "Username already exists",
  DUPLICATE_EMAIL = "Email already exists",
  INVALID_LOGIN = "Invalid login",
  INVALID_PASSWORD = "Invalid password",
  INVALID_TOKEN = "Invalid token",
  UNAUTHORIZED = "Unauthorized",
  TOKENEXPIRED = "Token expired",
  PARAMS_MISSING = "Params missing",
  ALREADY_FOLLOWER = "You already follow this user",
  ALREADY_UNFOLLOWER = "You already unfollow this user",
}
